<?php
$this->load->view('essentials/hasNoSessionChecker.php');
$this->load->view('essentials/headerSrc.php');
$this->load->view('essentials/headerMenu.php');
$this->load->view('essentials/Sidebar.php');
$this->load->view('Sales/Sales.php');
$this->load->view('essentials/footer.php');
$this->load->view('essentials/footerSrc.php');
?>